baseurl = "/"
title = "Maiche Jewan"
theme = "hugo-nederburg-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = "www-maichejewan-netlify-com"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-87289291-1"
preserveTaxonomyNames = true
paginate = 30 #frontpage pagination

[params]
  slogan = "Traditional recipes with a touch of mum's love"
  description = "cooking,recipes,indian, mangalorean,blog" # meta description
  copyright = "&copy;2018 Maiche Jewan"
  author = "Maiche Jewan"
  authorLink = "https://maichejewan.com/"
  bio = [
    "Maiche Jewan is a culinary website with traditional home made recipies."
  ]


  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below (it is also used in Gravatar for the bio).
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "maichejewan@gmail.com" # if you change this the author pic changes

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  facebook      = "facebook.com/maichejewan"
  #googleplus    = "full profile url in googleplus"
  email         = "maichejewan@gmail.com"
  #twitter       = "full profile url in twitter"
  #linkedin      = "full profile url in linkedin"
 #stackoverflow = "full profile url in stackoverflow"
  instagram     = "instagram.com/maichejewan"
  #github        = "full profile url in github"
